"""
* @Author: Samarth BM.
* @Date: 2021-09-25 23:20  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 23:20
* @Title: To convert numpy array to list.

In [3]:
import numpy as np
from LogHandler import logger

try:

    arr = np.arange(9).reshape(3,3)
    print("Array is:\n", arr)

    list1 = arr.tolist()
    print("Converted array to list:\n",list1)

except Exception as e:
    logger.error(e)

Array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Converted array to list:
 [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
