"""
* @Author: Samarth BM.
* @Date: 2021-09-25 20:46  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 20:46
* @Title: To concatenate two arrays.

In [11]:
import numpy as np
from LogHandler import logger

try:
    
    arr1 = np.array([[1,2,3], [7,8,9]])
    arr2 = np.array([[4,5,6], [10,11,12]])
    arr3 = np.concatenate((arr1, arr2), axis=1)
    print("With axis 1\n",arr3)

    arr4= np.concatenate((arr1, arr2), axis=0)
    print("With axis 0\n",arr4)

    arr5= np.concatenate((arr1, arr2), axis=None)
    print("With axis None\n",arr5)

except Exception as e:
    logger.error(e)

With axis 1
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
With axis 0
 [[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
With axis None
 [ 1  2  3  7  8  9  4  5  6 10 11 12]
