"""
@Author: Samarth BM.
@Date: 2021-09-24 23:45  
@Last Modified by: Samarth BM
@Last Modified time: 2021-09-24 23:45
@Title: To create 3*3 matrix.
"""

In [3]:
import numpy as np
from LogHandler import logger

try:

    matrix = np.array([[2,3,4],[5,6,7],[8,9,10]])
    print("3*3 matrix is:\n",matrix)

except Exception as e:
    logger.error(e)


3*3 matrix is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
