"""
* @Author: Samarth BM.
* @Date: 2021-09-25 20:31  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 20:31
* @Title: To create a 3-D array with ones on a diagonal and zeros elsewhere.

In [17]:
import numpy as np
from LogHandler import logger

try:

    arr1 = np.eye(3)
    print("Array with ones on diagonal and zeros elsewhere:\n",arr1)

except Exception as e:
    logger.error(e)

Array with ones on diagonal and zeros elsewhere:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
