"""
* @Author: Samarth BM.
* @Date: 2021-09-25 19:52  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 19:52
* @Title: To create a flattened array.

In [2]:
import numpy as np
from LogHandler import logger

try:

    arr1 = np.array([[1, 2, 3], [4, 5, 6]])
    print("Original array:\n",arr1)
    print("Flattened array:\n",np.ravel(arr1))

except Exception as e:
    logger.error(e)

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]
