"""
* @Author: Samarth BM.
* @Date: 2021-09-25 10:11  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 10:11
* @Title: To convert list and tuple to array.
"""

In [12]:
import numpy as np
from LogHandler import logger

try:
    arr = np.array([1,2,3,4,5])
    print("List to array:\n", arr )
    logger.info("List converted to array")

    arr1 = np.array([[1,2,3],[4,5,6]])
    print("Tuple to array:\n",arr1)
    logger.info("Tuple converted to array")
except Exception as e:
    logger.error(e)

List to array:
 [1 2 3 4 5]
Tuple to array:
 [[1 2 3]
 [4 5 6]]
