"""
* @Author: Samarth BM.
* @Date: 2021-09-25 21:00  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 21:00
* @Title: To create an array of (3, 4) shape, multiply every element value by 3 
          and display the new array.

In [3]:
import numpy as np
from LogHandler import logger

try:
    
    arr = np.arange(12).reshape(3,4)
    print("Original array:\n",arr)

    print("Array after multiplying each value with 3:\n",arr*3)

except Exception as e:
    logger.error(e)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array after multiplying each value with 3:
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
