In [4]:
import numpy as np
from LogHandler import logger

try:
    
    arr = np.ones((5,5))
    print("Original Array:\n", arr)
    print("1 on the border and 0 inside the array: ")
    arr[1:-1, 1:-1] = 0
    print(arr)
    
except Exception as e:
    logger.error(e)

Original Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside the array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
