"""
* @Author: Samarth BM.
* @Date: 2021-09-25 00:35  
* @Last Modified by: Samarth BM
* @Last Modified time: 2021-09-25 00:35
* @Title: To add a border filled with 0's around an existing array.
"""

In [15]:
import numpy as np
from LogHandler import logger

try:

    arr = np.ones((3,3))
    print("Original array:\n",arr)
    print("0 on the border and 1 inside in the array")
    arr2 = np.pad(arr, (1,), 'constant', constant_values = 0)
    print(arr2)
    
except Exception as e:
    logger.error(e)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
